name: python wheel packages

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-13]

    steps:
      - uses: actions/checkout@v2
      - name: Checkout CMS
        uses: actions/checkout@v2
        with:
          repository: msoos/cryptominisat
          ref: 'master'
          path: python/cryptominisat
      - name: Checkout Arjun
        uses: actions/checkout@v2
        with:
          repository: meelgroup/arjun
          path: python/arjun

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        env:
          CIBW_BEFORE_ALL_LINUX: yum install -y boost-devel zlib-devel
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "pytest --color=yes -v {project}/python/tests/test_pyapproxmc.py"
          CIBW_SKIP: "*musl*"
          CIBW_ARCHS: "auto64"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
      - name: Install twine
        run: python -m pip install twine
      - name: Publish wheels to PyPI 
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload --skip-existing --disable-progress-bar ./wheelhouse/pyapproxmc-*.whl
