name: Python tarball build

on: [push, pull_request]
#  release:
#    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine flake8
    - name: Checkout CMS
      uses: actions/checkout@v2
      with:
        repository: msoos/cryptominisat
        ref: 'master'
        path: python/cryptominisat
    - name: Checkout Arjun
      uses: actions/checkout@v2
      with:
        repository: meelgroup/arjun
        path: python/arjun
#    - name: Lint with flake8 for syntax errors
#      run: |
#        pip install flake8
#        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Get Python3
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a source tarball
      run: >-
        python -m
        build
        --sdist
        --outdir dist/
    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.7.1
      with:
        build-requirements: 'cython numpy'
        system-packages: 'zlib-devel boost-devel boost-program-options boost-serialization'
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
       name: python-wheel-artifact
       path: |
         dist/*-manylinux*.whl
         dist/*.tar.gz
    - name: Publish wheels to PyPI
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        ls dist/
        twine upload --skip-existing --disable-progress-bar dist/pyapproxmc*.tar.gz
